apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-api
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: shubhampatil5128/nodeapp:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: zuul-api
spec:
  selector:
    app: nodeapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 3000
    nodePort: 32470
